{% set name = "opentelemetry-exporter-zipkin-proto-http" %}
{% set version = "1.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-zipkin-proto-http-{{ version }}.tar.gz
  sha256: 595fc729158e208c8e756553fb5ea52d85f6132e0ce161d0695be3f8c807a4bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-exporter-zipkin-json ==1.11.1
    - opentelemetry-sdk ~=1.11
    - protobuf >=3.12
    - python >=3.5
    - requests ~=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin-proto-http
  summary: Zipkin Span Protobuf Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
