{% set name = "opentelemetry-exporter-zipkin-proto-http" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_zipkin_proto_http-{{ version }}.tar.gz
  sha256: efd9fb13d52f42b482875a2fb342d6a425d0cda8c8f368045c5d371c715e628d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.3
    - opentelemetry-exporter-zipkin-json ==1.21.0
    - opentelemetry-sdk ~=1.11
    - protobuf ~=3.12
    - requests ~=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-zipkin-proto-http
  summary: Zipkin Span Protobuf Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
